// Copyright 2022, Mikhail Paulyshka
// SPDX-License-Identifier: MIT

namespace Mixaill.HwInfo.D3D.Interop
{
    /// <summary>
    /// Reference: d3dkmthk.h::_D3DKMT_QUERYSTATISTICS_TYPE
    /// </summary>
    public enum _D3DKMT_QUERYSTATISTICS_TYPE : uint
    {
        //WDDM 1.0
        D3DKMT_QUERYSTATISTICS_ADAPTER = 0,
        D3DKMT_QUERYSTATISTICS_PROCESS = 1,
        D3DKMT_QUERYSTATISTICS_PROCESS_ADAPTER = 2,
        D3DKMT_QUERYSTATISTICS_SEGMENT = 3,
        D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT = 4,
        D3DKMT_QUERYSTATISTICS_NODE = 5,
        D3DKMT_QUERYSTATISTICS_PROCESS_NODE = 6,
        D3DKMT_QUERYSTATISTICS_VIDPNSOURCE = 7,
        D3DKMT_QUERYSTATISTICS_PROCESS_VIDPNSOURCE = 8,

        //WDDM 2.1
        D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT_GROUP = 9,

        //WDDM 2.4
        D3DKMT_QUERYSTATISTICS_PHYSICAL_ADAPTER = 10,

        //WDDM 3.1
        D3DKMT_QUERYSTATISTICS_ADAPTER2 = 11,
        D3DKMT_QUERYSTATISTICS_SEGMENT2 = 12,
        D3DKMT_QUERYSTATISTICS_PROCESS_ADAPTER2 = 13,
        D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT2 = 14,
        D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT_GROUP2 = 15,
        D3DKMT_QUERYSTATISTICS_SEGMENT_USAGE = 16,
        D3DKMT_QUERYSTATISTICS_SEGMENT_GROUP_USAGE = 17,
        D3DKMT_QUERYSTATISTICS_NODE2 = 18,
        D3DKMT_QUERYSTATISTICS_PROCESS_NODE2 = 19
    }
}
